server:
  port: ${SERVER_PORT}

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  r2dbc:
    url: ${R2DBC_URL}
    username: ${R2DBC_USERNAME}
    password: ${R2DBC_PASSWORD}
    pool:
      enabled: ${R2DBC_POOL_ENABLED}
      initial-size: ${R2DBC_POOL_INITIAL_SIZE}
      max-idle-time: ${R2DBC_POOL_MAX_IDLE_TIME}
      max-size: ${R2DBC_POOL_MAX_SIZE}

  liquibase:
    change-log: ${LIQUIBASE_CHANGE_LOG}

logging:
  level:
    io.r2dbc.postgresql.QUERY: ${LOGGING_LEVEL_IO_R2DBC_POSTGRESQL_QUERY}
    io.r2dbc.postgresql.PARAM: ${LOGGING_LEVEL_IO_R2DBC_POSTGRESQL_PARAM}
    io.netty.resolver.dns.DnsServerAddressStreamProviders: ${LOGGING_LEVEL_IO_NETTY_RESOLVER_DNS_DNS_SERVER_ADDRESS_STREAM_PROVIDERS}