server:
  port: 8080

spring:
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: redis
      port: 6379
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/wallet_db
    username: user
    password: password
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
  liquibase:
      change-log: classpath*:/db/changelog/db.changelog-master.yaml

logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    io.netty.resolver.dns.DnsServerAddressStreamProviders: off
