version: '3.9'

services:
  wallet-service:
    image: webbnba/wallet-service:v3
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=standalone
      - SPRING_R2DBC_URL=r2dbc:postgresql://db:5432/wallet_db
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=password
    depends_on:
      - db
      - redis
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
        reservations:
          cpus: "0.5"
          memory: 512M
    networks:
      - app-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: wallet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wallet-service
    networks:
      - app-network

volumes:
  db_data:
  redis_data:

networks:
  app-network:
    driver: bridge